### ISSUE TITLE
いいねボタン

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/booQ-UI#133]

**Comment by ryoha000** [comment]
@sapphi-red
アニメーションつけようと思ったんだけどsvgとcssアニメーションでゴリっと書くのと画像スライドさせるのどっちの方がいいと思う？
どっちもコピペするだけだから実装難易度は低い

**Comment by ryoha000** [comment]
あ～、画像の方はtwitterからとってきてるだけだから著作権怪しいかも
コードには著作権ないやろ！ｗ

**Comment by sapphi-red** [comment]
っぽいやつをつくるのは大丈夫だと思うけど同じものつくるのは流石にアウトだと思うよ
