### ISSUE TITLE
一括で借りる機能

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/booQ-UI#137]

**Comment by ryoha000** [comment]
これどう実装するって言ったっけ？
旧booQの方はstoreにもってたけど変えた方が良くない？って言われた気がする

**Comment by sapphi-red** [comment]
忘れちゃった
たぶんstoreなのはよくて、デザインかな…わからず

**Comment by ryoha000** [comment]
右上にカートモードのtoggleのボタンがあって、カートモードだとクリックがカートに入れるになる、みたいな

**Comment by ryoha000** [comment]
amazon形式
