### ISSUE TITLE
借りた/返した後にすぐに状態が反映されない

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/booQ-UI#147]

**Comment by ryoha000** [comment]
これってreloadさせたらいいかな？それともイベント渡してあげてjs上で交信させればいいかな？

**Comment by sapphi-red** [comment]
リロードはSPAの意味とは…になっちゃうからイベント来たら再取得でいいと思う

**Comment by sapphi-red** [comment]
↑これできるなら再取得じゃなくてPOSTの結果をレスポンスでもらいたいけどね
