### ISSUE TITLE
カレンダー

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/booQ-UI#346]
https://github.com/nathanreyes/v-calendar/blob/next/README.md

Safariだと`<input type="date">`に対応してないので結構ほしそう

**Comment by sapphi-red** [comment]
https://antoniandre.github.io/vue-cal/
こっちでもよさそう？

**Comment by ryoha000** [comment]
v-calendarの方が丸くてかわいくない？

**Comment by sapphi-red** [comment]
デザインあんまり考えないで張った
v-calenderでできそうなら問題ない

**Comment by ryoha000** [comment]
あー動きはするよ

**Comment by ryoha000** [comment]
サジェストがないから何が引数かソース見ないと分からんくてめんどくさいってだけ
