### ISSUE TITLE
備品には所有者を追加できない？

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/booQ-UI#488]
@ryoha000 これって仕様だよね？
いまいち追加できないのがどういう条件かわからず

追加できないならボタンを非表示にしたほうがよさそう

**Comment by ryoha000** [comment]
仕様
薄い記憶によると先に個人のアイテムがあったとき、traPをオーナーに追加(備品区分にはならない)はできた気がする
非表示は同意
