### ISSUE TITLE
登録時にadminじゃなくてもtraPが出てくる

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/booQ-UI#630]
![image](https://user-images.githubusercontent.com/49056869/159664592-f377e952-bc84-4276-a0a7-5a6f4d624030.png)
https://booq.trap.jp/items/new

**Comment by sapphi-red** [comment]
そもそも所有者は自身だけだからadminでないなら項目自体を非表示にするのがよさそう

**Comment by nokhnaton** [comment]
noc7t
