### ISSUE TITLE
urlを指定して画像を登録するやつが動かない？

### ISSUE THREAD

**Issue by ryoha000** [traPtitech/booQ-UI#641]
普通にクロスオリジンではじかれるんだけどどういう流れで実装したんだっけ？
@sapphi-red

**Comment by sapphi-red** [comment]
corbで弾かれる？corbならサイト側の問題で、そのじゃないなら何で弾かれる？imgタグはcorsは引っかからないはず

**Comment by ryoha000** [comment]
なんか画像コピーしたと思ったら`text/html`だったわ
:gahaha:
